/* ============================================================
   LP04 · Rundenspiele mit Makey Makey — Daten der vier Pfade
   Block-Notation: "kat: Text" pro Zeile, Einrückung = 2 Leerzeichen
   (x) Eingabefeld · [x] Auswahl · {kat x} Reporter · ⟨kat x⟩ Bedingung
   ============================================================ */
var CTRL_PAD = {
  // Steuerkreuz + Aktionstaste; action = Beschriftung der Leertaste
  pad: function (action) {
    return { pads: [
      { x: 72, y: 62, w: 38, h: 38, t: '↑', route: [[72, 0]], key: '↑' },
      { x: 30, y: 104, w: 38, h: 38, t: '←', route: [[30, 0]], key: '←' },
      { x: 114, y: 104, w: 38, h: 38, t: '→', route: [[124, 104], [124, 0]], key: '→' },
      { x: 72, y: 146, w: 38, h: 38, t: '↓', route: [[72, 178], [164, 178], [164, 0]], key: '↓' },
      { x: 222, y: 104, r: 36, t: action, route: [[222, 0]], key: 'SPACE' }
    ] };
  },
  einwurf: function () {
    return { pads: [
      { x: 60, y: 110, w: 56, h: 44, t: '←', route: [[60, 0]], key: '←' },
      { x: 237, y: 110, w: 56, h: 44, t: '→', route: [[237, 0]], key: '→' },
      { x: 148, y: 110, r: 40, t: 'EINWURF', route: [[148, 0]], key: 'SPACE' }
    ], deco: 'c4' };
  },
  tttFeld: function () {
    var keys = ['W', 'A', 'S', 'D', 'F', 'G', '←', '↓', '→'];
    var pads = [], xs = [96, 148, 200], ys = [50, 102, 154];
    var routes = [
      [[96, 0]], [[148, 0]], [[200, 0]],
      [[0, 102]], [[122, 102], [122, 128], [0, 128]], [[297, 102]],
      [[0, 154]], [[148, 210]], [[297, 154]]
    ];
    for (var i = 0; i < 9; i++) pads.push({ x: xs[i % 3], y: ys[Math.floor(i / 3)], w: 42, h: 42, t: String(i + 1), route: routes[i], key: keys[i] });
    return { pads: pads };
  },
  c4Feld: function () {
    var keys = ['W', 'A', 'S', 'D', 'F', 'G', 'SPACE'], pads = [];
    for (var i = 0; i < 7; i++) pads.push({ x: 40 + i * 36, y: 110, w: 28, h: 130, t: String(i + 1), route: [[40 + i * 36, 0]], key: keys[i] });
    return { pads: pads };
  }
};

var GAMES = [
/* ------------------------------------------------------------ TIC TAC TOE */
{ id: 'ttt', icon: '✕○', title: 'Tic Tac Toe', level: 'Einstieg', color: '#34ff9e',
  blurb: '3 × 3 Felder, Cursor mit Pfeilen, SPACE setzt. Ideal für den Start.',
  denk: [
    ['Gedächtnis', 'Was muss sich dein Spiel die ganze Zeit merken?', 'Wer gerade dran ist (Variable <code>Spieler</code>: 1 oder 2) und welche Felder schon belegt sind — dafür passt eine <b>Liste</b> <code>Feld</code> mit 9 Einträgen.'],
    ['5 Tasten, 9 Felder', 'Wie wählst du mit nur fünf Tasten eines von neun Feldern?', 'Ein <b>Cursor</b> (Rahmen) wird mit den Pfeiltasten bewegt. Zwei Variablen <code>spalte</code> und <code>zeile</code> (je 1–3) merken sich, wo er steht. SPACE bestätigt.'],
    ['Rechnen statt malen', 'Wie wird aus (spalte, zeile) eine Position auf der Bühne?', 'Bei 100 px pro Feld: <code>x = (spalte − 2) · 100</code>, <code>y = (2 − zeile) · 100</code>. Und die Feldnummer 1–9: <code>(zeile − 1) · 3 + spalte</code>.'],
    ['Gültiger Zug', 'Wann darf ein Stein gesetzt werden — und wann nicht?', 'Nur wenn das Feld noch leer ist: <code>Element (Nr) von [Feld] = -</code>.'],
    ['Spielende', 'Woran erkennt das Programm einen Sieg oder ein Unentschieden?', 'Es gibt genau <b>8 Gewinnlinien</b> (3 Zeilen, 3 Spalten, 2 Diagonalen). Nach 9 Zügen ohne Sieger: Unentschieden.'],
    ['Controller', 'Wie sieht euer A4-Controller aus?', 'Steuerkreuz ↑ ↓ ← → plus große SPACE-Taste „SETZEN“. Profi: neun Folienfelder wie das echte Spielfeld (Bauplan in Stufe 1).']
  ],
  stages: [
    { t: 'Controller & Spielfeld', time: '≈ 8 Min.',
      goal: 'Controller bauen und in Scratch Bühne und Figur vorbereiten.',
      html: '<ul><li>A4-Controller nach Bauplan bauen und im Controller-Test prüfen.</li><li><b>Bühnenbild</b> malen: 3 × 3-Gitter, Linien bei x = ±50 und y = ±50 (jedes Feld 100 px).</li><li>Neue Figur <b>Zeiger</b> mit drei Kostümen: <code>Rahmen</code> (gelbes Quadrat, 90 px, ohne Füllung), <code>X</code>, <code>O</code>.</li><li>Erweiterung <b>Malstift</b> hinzufügen (unten links) — für den Block <code>hinterlasse Abdruck</code>.</li></ul>',
      ctrl: [['pad', 'SETZEN', 'Basis-Controller: Steuerkreuz + SETZEN'], ['tttFeld', '', 'Profi: Feld-Controller — jedes Feld eine eigene Taste (W–G über Steckkabel an der Rückseite)']],
      code: [['Hardware-Test (Zeiger)', 'ev: Wenn Taste [Leertaste] gedrückt wird\nlook: sage (Klick!) für (0.5) Sekunden']] },
    { t: 'Cursor steuern', time: '≈ 7 Min.',
      goal: 'Der Rahmen springt mit den Pfeiltasten von Feld zu Feld — und bleibt im Spielfeld.',
      html: '<p>Lege die Variablen <code>spalte</code> und <code>zeile</code> an. In der Endlosschleife: pro Pfeiltaste eine Verzweigung mit zwei Bedingungen (Taste gedrückt <b>und</b> Rand noch nicht erreicht). Danach entprellen!</p>',
      tip: 'Baue erst „rechts“ fertig und teste. Dann Rechtsklick → Duplizieren und für links (<code>spalte &gt; 1</code>, um −1), unten (<code>zeile &lt; 3</code>, um 1) und oben (<code>zeile &gt; 1</code>, um −1) anpassen.',
      code: [['Zeiger', 'ev: Wenn ⚑ angeklickt wird\nvar: setze [spalte] auf (2)\nvar: setze [zeile] auf (2)\nlook: wechsle zu Kostüm [Rahmen]\nctl: wiederhole fortlaufend\n  ctl: falls ⟨op ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩ und ⟨op {var spalte} < (3)⟩⟩, dann\n    var: ändere [spalte] um (1)\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩⟩\n  note: … genauso für links, unten, oben\n  mot: gehe zu x: {op {op {var spalte} - (2)} * (100)} y: {op {op (2) - {var zeile}} * (100)}']] },
    { t: 'Setzen & Spielerwechsel', time: '≈ 5 Min.',
      goal: 'SPACE hinterlässt ein X oder O — danach ist die andere Person dran.',
      html: '<p>Variable <code>Spieler</code> am Start auf 1 setzen. Beim Setzen: passendes Kostüm wählen, Abdruck stempeln, zurück zum Rahmen, Spieler wechseln.</p>',
      tip: '<code>setze [Spieler] auf ((3) - (Spieler))</code> macht aus 1 eine 2 und aus 2 eine 1.',
      code: [['Zeiger · in die Schleife einbauen', 'ctl: falls ⟨sen Taste [Leertaste] gedrückt?⟩, dann\n  ctl: falls ⟨op {var Spieler} = (1)⟩, dann\n    look: wechsle zu Kostüm [X]\n  ctl: sonst\n    look: wechsle zu Kostüm [O]\n  pen: hinterlasse Abdruck\n  look: wechsle zu Kostüm [Rahmen]\n  var: setze [Spieler] auf {op (3) - {var Spieler}}\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Leertaste] gedrückt?⟩⟩']] },
    { t: 'Spielfeld-Gedächtnis', time: '≈ 5 Min.',
      goal: 'Ein Feld kann nur einmal belegt werden.',
      html: '<p>Lege eine Liste <code>Feld</code> an und fülle sie beim Start mit neun Strichen <code>-</code>. Vor dem Setzen berechnest du die Feldnummer und prüfst, ob dort noch <code>-</code> steht. Nach dem Setzen trägst du die Spielernummer ein.</p>',
      tip: 'Feldnummer: oben links = 1, oben rechts = 3, unten rechts = 9 → <code>(zeile − 1) · 3 + spalte</code>. Lass die Liste auf der Bühne anzeigen, dann siehst du beim Testen, was passiert.',
      code: [['Zeiger · Start ergänzen', 'pen: lösche alles\nlst: lösche alles aus [Feld]\nctl: wiederhole (9) mal\n  lst: füge (-) zu [Feld] hinzu'], ['Zeiger · Setzen mit Prüfung', 'var: setze [Nr] auf {op {op {op {var zeile} - (1)} * (3)} + {var spalte}}\nctl: falls ⟨op {lst Element {var Nr} von [Feld]} = (-)⟩, dann\n  lst: ersetze Element {var Nr} von [Feld] durch {var Spieler}\n  note: … Kostüm, Abdruck, Spielerwechsel wie in Stufe 3']] },
    { t: 'Gewinner finden', time: '≈ 5 Min.',
      goal: 'Nach jedem Zug prüft das Spiel alle 8 Linien und erkennt Sieg oder Unentschieden.',
      html: '<p>Lege unter <b>Meine Blöcke</b> einen Block <code>prüfe Linie (a) (b) (c)</code> mit drei Eingaben an. Er setzt <code>Sieger</code> auf den aktuellen Spieler, wenn alle drei Felder ihm gehören. Der Block <code>prüfe Gewinn</code> ruft ihn achtmal auf.</p>',
      tip: 'Die acht Linien: 1 2 3 · 4 5 6 · 7 8 9 · 1 4 7 · 2 5 8 · 3 6 9 · 1 5 9 · 3 5 7. Aus <code>wiederhole fortlaufend</code> wird jetzt <code>wiederhole bis ⟨Sieger &gt; 0⟩</code>.',
      code: [['Zeiger · eigene Blöcke', 'def: Definiere prüfe Linie {par a} {par b} {par c}\nctl: falls ⟨op ⟨op {lst Element {par a} von [Feld]} = {var Spieler}⟩ und ⟨op ⟨op {lst Element {par b} von [Feld]} = {var Spieler}⟩ und ⟨op {lst Element {par c} von [Feld]} = {var Spieler}⟩⟩⟩, dann\n  var: setze [Sieger] auf {var Spieler}\n\ndef: Definiere prüfe Gewinn\nmy: prüfe Linie (1) (2) (3)\nmy: prüfe Linie (4) (5) (6)\nmy: prüfe Linie (7) (8) (9)\nmy: prüfe Linie (1) (4) (7)\nmy: prüfe Linie (2) (5) (8)\nmy: prüfe Linie (3) (6) (9)\nmy: prüfe Linie (1) (5) (9)\nmy: prüfe Linie (3) (5) (7)\nctl: falls ⟨op ⟨op {var Sieger} = (0)⟩ und ⟨op {var Züge} = (9)⟩⟩, dann\n  var: setze [Sieger] auf (3)\n  note: 3 bedeutet: unentschieden']] }
  ],
  setup: [['Figuren', 'Zeiger (Kostüme: Rahmen, X, O)'], ['Variablen', 'Spieler · spalte · zeile · Nr · Züge · Sieger'], ['Listen', 'Feld (9 Einträge)'], ['Bühne', '3 × 3-Gitter, Feld = 100 px · Erweiterung Malstift']],
  plan: [
    ['Zeiger · Hauptskript', 'ev: Wenn ⚑ angeklickt wird\nvar: setze [Spieler] auf (1)\nvar: setze [spalte] auf (2)\nvar: setze [zeile] auf (2)\nvar: setze [Züge] auf (0)\nvar: setze [Sieger] auf (0)\npen: lösche alles\nlst: lösche alles aus [Feld]\nctl: wiederhole (9) mal\n  lst: füge (-) zu [Feld] hinzu\nlook: wechsle zu Kostüm [Rahmen]\nctl: wiederhole bis ⟨op {var Sieger} > (0)⟩\n  my: steuere Zeiger\n  mot: gehe zu x: {op {op {var spalte} - (2)} * (100)} y: {op {op (2) - {var zeile}} * (100)}\n  ctl: falls ⟨sen Taste [Leertaste] gedrückt?⟩, dann\n    my: setze Stein\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Leertaste] gedrückt?⟩⟩\nctl: falls ⟨op {var Sieger} = (3)⟩, dann\n  look: sage (Unentschieden!)\nctl: sonst\n  look: sage {op verbinde (Sieg für Spieler ) und {var Sieger}}'],
    ['Zeiger · steuere Zeiger', 'def: Definiere steuere Zeiger\nctl: falls ⟨op ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩ und ⟨op {var spalte} < (3)⟩⟩, dann\n  var: ändere [spalte] um (1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach links] gedrückt?⟩ und ⟨op {var spalte} > (1)⟩⟩, dann\n  var: ändere [spalte] um (-1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach links] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach unten] gedrückt?⟩ und ⟨op {var zeile} < (3)⟩⟩, dann\n  var: ändere [zeile] um (1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach unten] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach oben] gedrückt?⟩ und ⟨op {var zeile} > (1)⟩⟩, dann\n  var: ändere [zeile] um (-1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach oben] gedrückt?⟩⟩'],
    ['Zeiger · setze Stein', 'def: Definiere setze Stein\nvar: setze [Nr] auf {op {op {op {var zeile} - (1)} * (3)} + {var spalte}}\nctl: falls ⟨op {lst Element {var Nr} von [Feld]} = (-)⟩, dann\n  lst: ersetze Element {var Nr} von [Feld] durch {var Spieler}\n  ctl: falls ⟨op {var Spieler} = (1)⟩, dann\n    look: wechsle zu Kostüm [X]\n  ctl: sonst\n    look: wechsle zu Kostüm [O]\n  pen: hinterlasse Abdruck\n  look: wechsle zu Kostüm [Rahmen]\n  var: ändere [Züge] um (1)\n  my: prüfe Gewinn\n  var: setze [Spieler] auf {op (3) - {var Spieler}}'],
    ['Zeiger · Gewinnprüfung', 'def: Definiere prüfe Gewinn\nmy: prüfe Linie (1) (2) (3)\nmy: prüfe Linie (4) (5) (6)\nmy: prüfe Linie (7) (8) (9)\nmy: prüfe Linie (1) (4) (7)\nmy: prüfe Linie (2) (5) (8)\nmy: prüfe Linie (3) (6) (9)\nmy: prüfe Linie (1) (5) (9)\nmy: prüfe Linie (3) (5) (7)\nctl: falls ⟨op ⟨op {var Sieger} = (0)⟩ und ⟨op {var Züge} = (9)⟩⟩, dann\n  var: setze [Sieger] auf (3)\n\ndef: Definiere prüfe Linie {par a} {par b} {par c}\nctl: falls ⟨op ⟨op {lst Element {par a} von [Feld]} = {var Spieler}⟩ und ⟨op ⟨op {lst Element {par b} von [Feld]} = {var Spieler}⟩ und ⟨op {lst Element {par c} von [Feld]} = {var Spieler}⟩⟩⟩, dann\n  var: setze [Sieger] auf {var Spieler}']
  ],
  extra: '<b>Weiter geht’s:</b> Feld-Controller (9 Tasten) — jede Taste setzt direkt: <code>Wenn Taste [w] gedrückt wird → setze spalte 1, zeile 1, setze Stein</code>. Oder: Siege über mehrere Runden in <code>Punkte X</code>/<code>Punkte O</code> zählen.'
},
/* ------------------------------------------------------------ VIER GEWINNT */
{ id: 'c4', icon: '●●', title: 'Vier gewinnt', level: 'Fortgeschritten', color: '#35e0ff',
  blurb: '7 Spalten, Steine fallen nach unten. Nur ←, → und EINWURF.',
  denk: [
    ['Weniger Tasten', 'Welche Tasten braucht man bei Vier gewinnt überhaupt?', 'Nur <b>←</b> und <b>→</b> für die Spalte und <b>SPACE</b> zum Einwerfen — die Zeile ergibt sich durch die „Schwerkraft“.'],
    ['Das Brett als Liste', 'Wie speicherst du 7 × 6 = 42 Felder?', 'In einer Liste <code>Brett</code> mit 42 Einträgen. Zeile 1 ist <b>unten</b>. Feldnummer: <code>(zeile − 1) · 7 + spalte</code>.'],
    ['Schwerkraft', 'Wie findest du heraus, wo der Stein landet?', 'Von unten (zeile 1) nach oben suchen, bis ein Feld leer ist. Ist Zeile 7 erreicht, ist die Spalte voll.'],
    ['Vier in einer Reihe', 'Muss man nach jedem Zug das ganze Brett prüfen?', 'Nein! Nur vom <b>neuen Stein</b> aus in 4 Richtungen: waagerecht, senkrecht, zwei Diagonalen. In jede Richtung vorwärts und rückwärts gleichfarbige Steine zählen — ab 4 gewinnt man.'],
    ['Animation', 'Wie sieht es echt aus, wenn ein Stein fällt?', 'Mit <code>gleite in (0.3) Sek. zu x: … y: …</code> von oben zur Zielposition, dann Abdruck.'],
    ['Controller', 'Wie sieht euer A4-Controller aus?', 'Einwurf-Leiste: ← · EINWURF · →. Profi: 7 Spalten-Streifen — Taste antippen = Stein in diese Spalte (W A S D F G + SPACE).']
  ],
  stages: [
    { t: 'Controller & Brett', time: '≈ 8 Min.',
      goal: 'Controller bauen, Bühne und Figur vorbereiten.',
      html: '<ul><li>Einwurf-Controller bauen und testen.</li><li><b>Bühnenbild</b>: blaues Brett mit 7 × 6 Löchern, Feld = 50 px. Mittelpunkte: x = (spalte − 4) · 50, y = (zeile − 1) · 50 − 145 (zeile 1 = unten).</li><li>Figur <b>Chip</b> mit Kostümen <code>Pfeil</code> (zeigt nach unten), <code>Rot</code>, <code>Gelb</code> (Kreise, 44 px).</li><li>Erweiterung <b>Malstift</b> hinzufügen.</li></ul>',
      ctrl: [['einwurf', '', 'Basis-Controller: Einwurf-Leiste'], ['c4Feld', '', 'Profi: 7 Spalten-Tasten (W–G über Steckkabel an der Rückseite, 7. Spalte = SPACE)']],
      code: [] },
    { t: 'Einwurf-Zeiger', time: '≈ 5 Min.',
      goal: 'Der Pfeil wandert über den Spalten hin und her (1 bis 7).',
      html: '<p>Variable <code>spalte</code> (Start: 4). Pfeil auf y = 160 über dem Brett. Mit Entprellen, sonst saust er an den Rand.</p>',
      code: [['Chip', 'ev: Wenn ⚑ angeklickt wird\nvar: setze [spalte] auf (4)\nlook: wechsle zu Kostüm [Pfeil]\nctl: wiederhole fortlaufend\n  ctl: falls ⟨op ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩ und ⟨op {var spalte} < (7)⟩⟩, dann\n    var: ändere [spalte] um (1)\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩⟩\n  ctl: falls ⟨op ⟨sen Taste [Pfeil nach links] gedrückt?⟩ und ⟨op {var spalte} > (1)⟩⟩, dann\n    var: ändere [spalte] um (-1)\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach links] gedrückt?⟩⟩\n  mot: gehe zu x: {op {op {var spalte} - (4)} * (50)} y: (160)']] },
    { t: 'Schwerkraft', time: '≈ 7 Min.',
      goal: 'Beim Einwerfen findet das Programm das unterste freie Feld der Spalte.',
      html: '<p>Liste <code>Brett</code> beim Start mit 42 × <code>-</code> füllen. Im Block <code>wirf ein</code> startest du bei zeile 1 und gehst nach oben, solange das Feld belegt ist. Praktisch: Die Feldnummer <code>Nr</code> wächst dabei jeweils um 7 (eine Zeile höher).</p>',
      tip: 'Wenn die Schleife bei zeile 7 endet, ist die Spalte voll → Meldung statt Stein.',
      code: [['Chip · Start ergänzen', 'lst: lösche alles aus [Brett]\nctl: wiederhole (42) mal\n  lst: füge (-) zu [Brett] hinzu'], ['Chip · Freies Feld suchen', 'def: Definiere wirf ein\nvar: setze [zeile] auf (1)\nvar: setze [Nr] auf {var spalte}\nctl: wiederhole bis ⟨op ⟨op {var zeile} > (6)⟩ oder ⟨op {lst Element {var Nr} von [Brett]} = (-)⟩⟩\n  var: ändere [zeile] um (1)\n  var: ändere [Nr] um (7)\nctl: falls ⟨op {var zeile} < (7)⟩, dann\n  lst: ersetze Element {var Nr} von [Brett] durch {var Spieler}\n  note: hier kommt in Stufe 4 der Stein dazu\nctl: sonst\n  look: sage (Spalte voll!) für (1) Sekunden']] },
    { t: 'Stein fällt & Wechsel', time: '≈ 5 Min.',
      goal: 'Der Stein gleitet in sein Feld, bleibt als Abdruck liegen und der Spieler wechselt.',
      html: '<p>Ergänze im <code>falls zeile &lt; 7</code>-Teil: Farbe wählen, gleiten, stempeln, zurück zum Pfeil, Spieler wechseln. In der Hauptschleife: <code>falls Taste [Leertaste] gedrückt? → wirf ein</code>, danach entprellen.</p>',
      code: [['Chip · in „wirf ein“ ergänzen', 'ctl: falls ⟨op {var Spieler} = (1)⟩, dann\n  look: wechsle zu Kostüm [Rot]\nctl: sonst\n  look: wechsle zu Kostüm [Gelb]\nmot: gleite in (0.3) Sek. zu x: {op {op {var spalte} - (4)} * (50)} y: {op {op {op {var zeile} - (1)} * (50)} - (145)}\npen: hinterlasse Abdruck\nlook: wechsle zu Kostüm [Pfeil]\nvar: ändere [Züge] um (1)\nvar: setze [Spieler] auf {op (3) - {var Spieler}}']] },
    { t: 'Vier in einer Reihe', time: '≈ 8 Min.',
      goal: 'Nach jedem Stein wird geprüft, ob vier gleiche Steine in einer Reihe liegen.',
      html: '<p>Drei eigene Blöcke arbeiten zusammen: <code>zähle (dx) (dy)</code> läuft vom neuen Stein aus in eine Richtung und zählt gleichfarbige Steine. <code>prüfe Richtung (dx) (dy)</code> zählt vorwärts und rückwärts. <code>prüfe Gewinn</code> testet die 4 Richtungen.</p>',
      tip: 'Richtungen (dx | dy): waagerecht (1 | 0) · senkrecht (0 | 1) · Diagonale ↗ (1 | 1) · Diagonale ↘ (1 | −1). Wichtig: <code>prüfe Gewinn</code> <b>vor</b> dem Spielerwechsel aufrufen!',
      code: [['Chip · Gewinnprüfung', 'def: Definiere zähle {par dx} {par dy}\nvar: setze [s] auf {op {var spalte} + {par dx}}\nvar: setze [z] auf {op {var zeile} + {par dy}}\nvar: setze [weiter] auf (1)\nctl: wiederhole bis ⟨op {var weiter} = (0)⟩\n  ctl: falls ⟨op ⟨op ⟨op {var s} > (0)⟩ und ⟨op {var s} < (8)⟩⟩ und ⟨op ⟨op {var z} > (0)⟩ und ⟨op {var z} < (7)⟩⟩⟩, dann\n    ctl: falls ⟨op {lst Element {op {op {op {var z} - (1)} * (7)} + {var s}} von [Brett]} = {var Spieler}⟩, dann\n      var: ändere [Anzahl] um (1)\n      var: ändere [s] um {par dx}\n      var: ändere [z] um {par dy}\n    ctl: sonst\n      var: setze [weiter] auf (0)\n  ctl: sonst\n    var: setze [weiter] auf (0)\n\ndef: Definiere prüfe Richtung {par dx} {par dy}\nvar: setze [Anzahl] auf (1)\nmy: zähle {par dx} {par dy}\nmy: zähle {op (0) - {par dx}} {op (0) - {par dy}}\nctl: falls ⟨op {var Anzahl} > (3)⟩, dann\n  var: setze [Sieger] auf {var Spieler}\n\ndef: Definiere prüfe Gewinn\nmy: prüfe Richtung (1) (0)\nmy: prüfe Richtung (0) (1)\nmy: prüfe Richtung (1) (1)\nmy: prüfe Richtung (1) (-1)\nctl: falls ⟨op ⟨op {var Sieger} = (0)⟩ und ⟨op {var Züge} = (42)⟩⟩, dann\n  var: setze [Sieger] auf (3)']] }
  ],
  setup: [['Figuren', 'Chip (Kostüme: Pfeil, Rot, Gelb)'], ['Variablen', 'Spieler · spalte · zeile · Nr · Züge · Sieger · s · z · weiter · Anzahl'], ['Listen', 'Brett (42 Einträge, zeile 1 = unten)'], ['Bühne', '7 × 6 Löcher, Feld = 50 px · Erweiterung Malstift']],
  plan: [
    ['Chip · Hauptskript', 'ev: Wenn ⚑ angeklickt wird\nvar: setze [Spieler] auf (1)\nvar: setze [spalte] auf (4)\nvar: setze [Züge] auf (0)\nvar: setze [Sieger] auf (0)\npen: lösche alles\nlst: lösche alles aus [Brett]\nctl: wiederhole (42) mal\n  lst: füge (-) zu [Brett] hinzu\nlook: wechsle zu Kostüm [Pfeil]\nctl: wiederhole bis ⟨op {var Sieger} > (0)⟩\n  ctl: falls ⟨op ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩ und ⟨op {var spalte} < (7)⟩⟩, dann\n    var: ändere [spalte] um (1)\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩⟩\n  ctl: falls ⟨op ⟨sen Taste [Pfeil nach links] gedrückt?⟩ und ⟨op {var spalte} > (1)⟩⟩, dann\n    var: ändere [spalte] um (-1)\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach links] gedrückt?⟩⟩\n  mot: gehe zu x: {op {op {var spalte} - (4)} * (50)} y: (160)\n  ctl: falls ⟨sen Taste [Leertaste] gedrückt?⟩, dann\n    my: wirf ein\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Leertaste] gedrückt?⟩⟩\nctl: falls ⟨op {var Sieger} = (3)⟩, dann\n  look: sage (Unentschieden!)\nctl: sonst\n  look: sage {op verbinde (Sieg für Spieler ) und {var Sieger}}'],
    ['Chip · wirf ein', 'def: Definiere wirf ein\nvar: setze [zeile] auf (1)\nvar: setze [Nr] auf {var spalte}\nctl: wiederhole bis ⟨op ⟨op {var zeile} > (6)⟩ oder ⟨op {lst Element {var Nr} von [Brett]} = (-)⟩⟩\n  var: ändere [zeile] um (1)\n  var: ändere [Nr] um (7)\nctl: falls ⟨op {var zeile} < (7)⟩, dann\n  lst: ersetze Element {var Nr} von [Brett] durch {var Spieler}\n  ctl: falls ⟨op {var Spieler} = (1)⟩, dann\n    look: wechsle zu Kostüm [Rot]\n  ctl: sonst\n    look: wechsle zu Kostüm [Gelb]\n  mot: gleite in (0.3) Sek. zu x: {op {op {var spalte} - (4)} * (50)} y: {op {op {op {var zeile} - (1)} * (50)} - (145)}\n  pen: hinterlasse Abdruck\n  look: wechsle zu Kostüm [Pfeil]\n  var: ändere [Züge] um (1)\n  my: prüfe Gewinn\n  var: setze [Spieler] auf {op (3) - {var Spieler}}\nctl: sonst\n  look: sage (Spalte voll!) für (1) Sekunden'],
    ['Chip · Gewinnprüfung', 'def: Definiere prüfe Gewinn\nmy: prüfe Richtung (1) (0)\nmy: prüfe Richtung (0) (1)\nmy: prüfe Richtung (1) (1)\nmy: prüfe Richtung (1) (-1)\nctl: falls ⟨op ⟨op {var Sieger} = (0)⟩ und ⟨op {var Züge} = (42)⟩⟩, dann\n  var: setze [Sieger] auf (3)\n\ndef: Definiere prüfe Richtung {par dx} {par dy}\nvar: setze [Anzahl] auf (1)\nmy: zähle {par dx} {par dy}\nmy: zähle {op (0) - {par dx}} {op (0) - {par dy}}\nctl: falls ⟨op {var Anzahl} > (3)⟩, dann\n  var: setze [Sieger] auf {var Spieler}'],
    ['Chip · zähle', 'def: Definiere zähle {par dx} {par dy}\nvar: setze [s] auf {op {var spalte} + {par dx}}\nvar: setze [z] auf {op {var zeile} + {par dy}}\nvar: setze [weiter] auf (1)\nctl: wiederhole bis ⟨op {var weiter} = (0)⟩\n  ctl: falls ⟨op ⟨op ⟨op {var s} > (0)⟩ und ⟨op {var s} < (8)⟩⟩ und ⟨op ⟨op {var z} > (0)⟩ und ⟨op {var z} < (7)⟩⟩⟩, dann\n    ctl: falls ⟨op {lst Element {op {op {op {var z} - (1)} * (7)} + {var s}} von [Brett]} = {var Spieler}⟩, dann\n      var: ändere [Anzahl] um (1)\n      var: ändere [s] um {par dx}\n      var: ändere [z] um {par dy}\n    ctl: sonst\n      var: setze [weiter] auf (0)\n  ctl: sonst\n    var: setze [weiter] auf (0)']
  ],
  extra: '<b>Weiter geht’s:</b> Spalten-Controller mit 7 Tasten — <code>Wenn Taste [w] gedrückt wird → setze spalte auf 1, wirf ein</code> usw. Oder: den Gewinnerstein blinken lassen.'
},
/* ------------------------------------------------------------ SCHIFFE VERSENKEN */
{ id: 'sv', icon: '⚓', title: 'Schiffe versenken', level: 'Fortgeschritten', color: '#a56bff',
  blurb: '6 × 6-Seekarte, Zielkreuz, FEUER. Flotten versteckt der Computer.',
  denk: [
    ['Geheime Flotten', 'Beide sitzen vor demselben Bildschirm — wie bleiben die Schiffe geheim?', 'Der <b>Computer</b> versteckt die Flotten per Zufall. Auf der Bühne wird immer nur die <b>gegnerische</b> Seekarte gezeigt — und davon nur Treffer und Fehlschüsse.'],
    ['Zwei Meere, eine Liste', 'Wie speicherst du zwei 6 × 6-Meere?', 'Eine Liste <code>Meer</code> mit 72 Einträgen: 1–36 gehören Flotte 1, 37–72 Flotte 2. Zeichen: <code>~</code> Wasser, <code>S</code> Schiff, <code>x</code> Treffer, <code>o</code> daneben.'],
    ['Auf wen schieße ich?', 'Wie rechnest du die Feldnummer in der Flotte des Gegners aus?', 'Spieler 1 zielt auf Flotte 2 und umgekehrt: <code>Nr = (2 − Spieler) · 36 + (zeile − 1) · 6 + spalte</code>.'],
    ['Wer ist dran?', 'Wann wechselt der Spieler?', 'Klassische Regel: Bei <b>Wasser</b> ist der andere dran, bei <b>Treffer</b> darf man noch einmal schießen.'],
    ['Seekarte zeichnen', 'Wie zeigst du nach dem Wechsel die andere Seekarte?', 'Mit <code>lösche alles</code> und einer Schleife über 36 Felder: Für jedes <code>x</code> oder <code>o</code> Kostüm wechseln, hinfahren, Abdruck. Eigener Block <b>ohne Bildschirmaktualisierung</b> — dann geht es blitzschnell.'],
    ['Controller', 'Wie sieht euer A4-Controller aus?', 'Steuerkreuz + große SPACE-Taste „FEUER“. Zeichnet die Seekarte (A–F, 1–6) daneben auf das Blatt — als Spickzettel für eigene Notizen.']
  ],
  stages: [
    { t: 'Controller & Seekarte', time: '≈ 7 Min.',
      goal: 'Controller bauen, Bühne und Figur vorbereiten.',
      html: '<ul><li>Steuerkreuz-Controller mit FEUER-Taste bauen und testen.</li><li><b>Bühnenbild</b>: Meer mit 6 × 6-Gitter, Feld = 50 px, Beschriftung A–F / 1–6. Mittelpunkte: x = (spalte − 3,5) · 50, y = (3,5 − zeile) · 50.</li><li>Figur <b>Zielkreuz</b> mit Kostümen <code>Kreuz</code>, <code>Treffer</code> (rotes X / Flamme), <code>Wasser</code> (weißer Kringel).</li><li>Erweiterung <b>Malstift</b> hinzufügen.</li></ul>',
      ctrl: [['pad', 'FEUER', 'Controller: Steuerkreuz + FEUER']], code: [] },
    { t: 'Zielkreuz steuern', time: '≈ 5 Min.',
      goal: 'Das Zielkreuz bewegt sich auf dem 6 × 6-Gitter.',
      html: '<p>Wie bei Tic Tac Toe: <code>spalte</code> und <code>zeile</code> von 1 bis 6, vier Verzweigungen mit Rand-Prüfung und Entprellen. Den Block <code>steuere Zielkreuz</code> legst du am besten als eigenen Block an.</p>',
      code: [['Zielkreuz', 'def: Definiere steuere Zielkreuz\nctl: falls ⟨op ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩ und ⟨op {var spalte} < (6)⟩⟩, dann\n  var: ändere [spalte] um (1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩⟩\nnote: … genauso für links (> 1), unten (zeile < 6), oben (zeile > 1)\n\nev: Wenn ⚑ angeklickt wird\nvar: setze [spalte] auf (1)\nvar: setze [zeile] auf (1)\nlook: wechsle zu Kostüm [Kreuz]\nctl: wiederhole fortlaufend\n  my: steuere Zielkreuz\n  mot: gehe zu x: {op {op {var spalte} - (3.5)} * (50)} y: {op {op (3.5) - {var zeile}} * (50)}']] },
    { t: 'Flotten verstecken', time: '≈ 6 Min.',
      goal: 'Jede Flotte bekommt 4 U-Boote (je 1 Feld) an zufälligen Stellen.',
      html: '<p>Liste <code>Meer</code> mit 72 × <code>~</code> füllen. Dann versteckt der Block <code>verstecke Schiffe (versatz)</code> vier U-Boote: Zufallsfeld wählen — ist dort Wasser, wird ein <code>S</code> eingetragen. Aufruf mit Versatz 0 (Flotte 1) und 36 (Flotte 2).</p>',
      tip: 'Zum Testen die Liste auf der Bühne anzeigen — im fertigen Spiel natürlich ausblenden (Häkchen weg)!',
      code: [['Zielkreuz', 'def: Definiere verstecke Schiffe {par versatz}\nvar: setze [gesetzt] auf (0)\nctl: wiederhole bis ⟨op {var gesetzt} = (4)⟩\n  var: setze [Nr] auf {op {par versatz} + {op Zufallszahl von (1) bis (36)}}\n  ctl: falls ⟨op {lst Element {var Nr} von [Meer]} = (~)⟩, dann\n    lst: ersetze Element {var Nr} von [Meer] durch (S)\n    var: ändere [gesetzt] um (1)\n\nnote: im Startskript:\nlst: lösche alles aus [Meer]\nctl: wiederhole (72) mal\n  lst: füge (~) zu [Meer] hinzu\nmy: verstecke Schiffe (0)\nmy: verstecke Schiffe (36)']] },
    { t: 'Feuer!', time: '≈ 6 Min.',
      goal: 'SPACE schießt auf das gewählte Feld der gegnerischen Flotte.',
      html: '<p>Liste <code>Treffer</code> mit zwei Einträgen (0 und 0) — einer pro Spieler. Treffer: <code>S</code> → <code>x</code>, Treffer zählen, nochmal schießen. Wasser: <code>~</code> → <code>o</code>, Spieler wechselt. Schon beschossene Felder bringen nichts.</p>',
      code: [['Zielkreuz', 'def: Definiere feuer\nvar: setze [Nr] auf {op {op {op (2) - {var Spieler}} * (36)} + {op {op {op {var zeile} - (1)} * (6)} + {var spalte}}}\nctl: falls ⟨op {lst Element {var Nr} von [Meer]} = (S)⟩, dann\n  lst: ersetze Element {var Nr} von [Meer] durch (x)\n  lst: ersetze Element {var Spieler} von [Treffer] durch {op {lst Element {var Spieler} von [Treffer]} + (1)}\n  look: sage (Treffer!) für (1) Sekunden\nctl: sonst\n  ctl: falls ⟨op {lst Element {var Nr} von [Meer]} = (~)⟩, dann\n    lst: ersetze Element {var Nr} von [Meer] durch (o)\n    look: sage (Wasser!) für (1) Sekunden\n    var: setze [Spieler] auf {op (3) - {var Spieler}}\nmy: zeichne Seekarte']] },
    { t: 'Seekarte & Sieg', time: '≈ 6 Min.',
      goal: 'Die Bühne zeigt immer die Karte des Gegners. Wer alle Schiffe trifft, gewinnt.',
      html: '<p>Rechtsklick auf den Block <code>zeichne Seekarte</code> → Bearbeiten → Häkchen bei <b>„Ohne Bildschirmaktualisierung laufen lassen“</b>. Aus Feldnummer <code>i</code> wird die Position: <code>sp = ((i − 1) mod 6) + 1</code>, <code>zl = abrunden((i − 1) / 6) + 1</code>.</p>',
      tip: 'Die Hauptschleife wird zu <code>wiederhole bis ⟨Element (Spieler) von [Treffer] = 4⟩</code> — gewonnen hat, wer gerade dran ist.',
      code: [['Zielkreuz', 'def: Definiere zeichne Seekarte\npen: lösche alles\nvar: setze [start] auf {op {op (2) - {var Spieler}} * (36)}\nvar: setze [i] auf (1)\nctl: wiederhole (36) mal\n  var: setze [Inhalt] auf {lst Element {op {var start} + {var i}} von [Meer]}\n  ctl: falls ⟨op ⟨op {var Inhalt} = (x)⟩ oder ⟨op {var Inhalt} = (o)⟩⟩, dann\n    ctl: falls ⟨op {var Inhalt} = (x)⟩, dann\n      look: wechsle zu Kostüm [Treffer]\n    ctl: sonst\n      look: wechsle zu Kostüm [Wasser]\n    var: setze [sp] auf {op {op {op {var i} - (1)} mod (6)} + (1)}\n    var: setze [zl] auf {op {op [abrunden] von {op {op {var i} - (1)} / (6)}} + (1)}\n    mot: gehe zu x: {op {op {var sp} - (3.5)} * (50)} y: {op {op (3.5) - {var zl}} * (50)}\n    pen: hinterlasse Abdruck\n  var: ändere [i] um (1)\nlook: wechsle zu Kostüm [Kreuz]']] },
    { t: 'Profi: echte Schiffe', time: 'Bonus',
      goal: 'Statt U-Booten: ein Kreuzer (3 Felder) und zwei Zerstörer (2 Felder), waagerecht oder senkrecht.',
      html: '<p>Zufällig Richtung und Startfeld wählen — so, dass das Schiff ins Meer passt. Dann prüfen, ob <b>alle</b> Felder frei sind; nur dann eintragen. Waagerecht liegen die Felder 1 auseinander, senkrecht 6.</p>',
      tip: 'Siegbedingung anpassen: 3 + 2 + 2 = 7 Treffer.',
      code: [['Zielkreuz', 'def: Definiere setze Schiff {par versatz} {par länge}\nvar: setze [fertig] auf (0)\nctl: wiederhole bis ⟨op {var fertig} = (1)⟩\n  ctl: falls ⟨op {op Zufallszahl von (1) bis (2)} = (1)⟩, dann\n    var: setze [sp] auf {op Zufallszahl von (1) bis {op (7) - {par länge}}}\n    var: setze [zl] auf {op Zufallszahl von (1) bis (6)}\n    var: setze [schritt] auf (1)\n  ctl: sonst\n    var: setze [sp] auf {op Zufallszahl von (1) bis (6)}\n    var: setze [zl] auf {op Zufallszahl von (1) bis {op (7) - {par länge}}}\n    var: setze [schritt] auf (6)\n  var: setze [Nr] auf {op {par versatz} + {op {op {op {var zl} - (1)} * (6)} + {var sp}}}\n  var: setze [frei] auf (1)\n  var: setze [k] auf (0)\n  ctl: wiederhole {par länge} mal\n    ctl: falls ⟨op nicht ⟨op {lst Element {op {var Nr} + {op {var k} * {var schritt}}} von [Meer]} = (~)⟩⟩, dann\n      var: setze [frei] auf (0)\n    var: ändere [k] um (1)\n  ctl: falls ⟨op {var frei} = (1)⟩, dann\n    var: setze [k] auf (0)\n    ctl: wiederhole {par länge} mal\n      lst: ersetze Element {op {var Nr} + {op {var k} * {var schritt}}} von [Meer] durch (S)\n      var: ändere [k] um (1)\n    var: setze [fertig] auf (1)']] }
  ],
  setup: [['Figuren', 'Zielkreuz (Kostüme: Kreuz, Treffer, Wasser)'], ['Variablen', 'Spieler · spalte · zeile · Nr · gesetzt · start · i · Inhalt · sp · zl'], ['Listen', 'Meer (72) · Treffer (2)'], ['Bühne', '6 × 6-Seekarte, Feld = 50 px · Erweiterung Malstift']],
  plan: [
    ['Zielkreuz · Hauptskript', 'ev: Wenn ⚑ angeklickt wird\nvar: setze [Spieler] auf (1)\nvar: setze [spalte] auf (1)\nvar: setze [zeile] auf (1)\nlst: lösche alles aus [Meer]\nctl: wiederhole (72) mal\n  lst: füge (~) zu [Meer] hinzu\nlst: lösche alles aus [Treffer]\nlst: füge (0) zu [Treffer] hinzu\nlst: füge (0) zu [Treffer] hinzu\nmy: verstecke Schiffe (0)\nmy: verstecke Schiffe (36)\nmy: zeichne Seekarte\nctl: wiederhole bis ⟨op {lst Element {var Spieler} von [Treffer]} = (4)⟩\n  my: steuere Zielkreuz\n  mot: gehe zu x: {op {op {var spalte} - (3.5)} * (50)} y: {op {op (3.5) - {var zeile}} * (50)}\n  ctl: falls ⟨sen Taste [Leertaste] gedrückt?⟩, dann\n    my: feuer\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Leertaste] gedrückt?⟩⟩\nlook: sage {op verbinde (Flotte versenkt! Sieg für Spieler ) und {var Spieler}}'],
    ['Zielkreuz · steuere Zielkreuz', 'def: Definiere steuere Zielkreuz\nctl: falls ⟨op ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩ und ⟨op {var spalte} < (6)⟩⟩, dann\n  var: ändere [spalte] um (1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach links] gedrückt?⟩ und ⟨op {var spalte} > (1)⟩⟩, dann\n  var: ändere [spalte] um (-1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach links] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach unten] gedrückt?⟩ und ⟨op {var zeile} < (6)⟩⟩, dann\n  var: ändere [zeile] um (1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach unten] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach oben] gedrückt?⟩ und ⟨op {var zeile} > (1)⟩⟩, dann\n  var: ändere [zeile] um (-1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach oben] gedrückt?⟩⟩'],
    ['Zielkreuz · verstecke Schiffe', 'def: Definiere verstecke Schiffe {par versatz}\nvar: setze [gesetzt] auf (0)\nctl: wiederhole bis ⟨op {var gesetzt} = (4)⟩\n  var: setze [Nr] auf {op {par versatz} + {op Zufallszahl von (1) bis (36)}}\n  ctl: falls ⟨op {lst Element {var Nr} von [Meer]} = (~)⟩, dann\n    lst: ersetze Element {var Nr} von [Meer] durch (S)\n    var: ändere [gesetzt] um (1)'],
    ['Zielkreuz · feuer', 'def: Definiere feuer\nvar: setze [Nr] auf {op {op {op (2) - {var Spieler}} * (36)} + {op {op {op {var zeile} - (1)} * (6)} + {var spalte}}}\nctl: falls ⟨op {lst Element {var Nr} von [Meer]} = (S)⟩, dann\n  lst: ersetze Element {var Nr} von [Meer] durch (x)\n  lst: ersetze Element {var Spieler} von [Treffer] durch {op {lst Element {var Spieler} von [Treffer]} + (1)}\n  look: sage (Treffer!) für (1) Sekunden\nctl: sonst\n  ctl: falls ⟨op {lst Element {var Nr} von [Meer]} = (~)⟩, dann\n    lst: ersetze Element {var Nr} von [Meer] durch (o)\n    look: sage (Wasser!) für (1) Sekunden\n    var: setze [Spieler] auf {op (3) - {var Spieler}}\nmy: zeichne Seekarte'],
    ['Zielkreuz · zeichne Seekarte (ohne Bildschirmaktualisierung)', 'def: Definiere zeichne Seekarte\npen: lösche alles\nvar: setze [start] auf {op {op (2) - {var Spieler}} * (36)}\nvar: setze [i] auf (1)\nctl: wiederhole (36) mal\n  var: setze [Inhalt] auf {lst Element {op {var start} + {var i}} von [Meer]}\n  ctl: falls ⟨op ⟨op {var Inhalt} = (x)⟩ oder ⟨op {var Inhalt} = (o)⟩⟩, dann\n    ctl: falls ⟨op {var Inhalt} = (x)⟩, dann\n      look: wechsle zu Kostüm [Treffer]\n    ctl: sonst\n      look: wechsle zu Kostüm [Wasser]\n    var: setze [sp] auf {op {op {op {var i} - (1)} mod (6)} + (1)}\n    var: setze [zl] auf {op {op [abrunden] von {op {op {var i} - (1)} / (6)}} + (1)}\n    mot: gehe zu x: {op {op {var sp} - (3.5)} * (50)} y: {op {op (3.5) - {var zl}} * (50)}\n    pen: hinterlasse Abdruck\n  var: ändere [i] um (1)\nlook: wechsle zu Kostüm [Kreuz]']
  ],
  extra: '<b>Weiter geht’s:</b> Stufe „Profi: echte Schiffe“ einbauen, Sounds für Treffer/Wasser, oder mit <code>CLICK</code> die eigene Flotte kurz anzeigen (nur wenn der Gegner wegschaut!).'
},
/* ------------------------------------------------------------ SCHACH */
{ id: 'ch', icon: '♞', title: 'Schach', level: 'Herausforderung', color: '#ffc23d',
  blurb: '8 × 8, Figur wählen & ziehen, Zugregeln. Für echte Profis.',
  denk: [
    ['Zwei Schritte pro Zug', 'Beim Schach reicht ein Tastendruck nicht. Warum?', 'Erst wird eine <b>eigene Figur gewählt</b>, dann das <b>Zielfeld</b>. Eine Variable <code>phase</code> („wählen“ / „ziehen“) merkt sich, wo man gerade ist.'],
    ['Das Brett als Text', 'Wie speicherst du 64 Felder mit verschiedenen Figuren?', 'Liste <code>Brett</code> mit 64 Kürzeln: Farbe + Figur, z. B. <code>wK</code> = weißer König, <code>sB</code> = schwarzer Bauer, <code>--</code> = leer. <code>Zeichen (1) von …</code> liefert die Farbe, <code>Zeichen (2) von …</code> den Typ.'],
    ['Aufstellung ohne Tipparbeit', 'Muss man 64 Einträge von Hand eingeben?', 'Nein: Die Startaufstellung als Textdatei herunterladen und in eine Liste <b>importieren</b> (Rechtsklick auf die Liste auf der Bühne → importieren).'],
    ['Zugregeln = Rechnen', 'Wie erkennt man, ob ein Springer richtig zieht?', 'Mit dem Abstand <code>dx</code>, <code>dy</code> zwischen Start und Ziel: Springer = (1 | 2) oder (2 | 1) in Beträgen. Turm: dx = 0 oder dy = 0. Läufer: |dx| = |dy|. König: beide ≤ 1.'],
    ['Weg frei?', 'Turm, Läufer und Dame dürfen nicht springen. Wie prüfst du das?', 'Schritt für Schritt vom Start Richtung Ziel gehen und jedes Feld dazwischen auf <code>--</code> prüfen.'],
    ['Vereinfachtes Ende', 'Schachmatt zu erkennen ist sehr schwer. Was geht einfacher?', '„Königsfang“: Wer den gegnerischen <b>König schlägt</b>, gewinnt. Rochade und en passant lassen wir weg.']
  ],
  stages: [
    { t: 'Controller & Brett', time: '≈ 7 Min.',
      goal: 'Controller bauen, Bühne und zwei Figuren vorbereiten.',
      html: '<ul><li>Steuerkreuz-Controller mit WÄHLEN-Taste. Optional CLICK als „Abbrechen“.</li><li><b>Bühnenbild</b>: 8 × 8-Schachbrett, Feld = 40 px. Mittelpunkte: x = (spalte − 4,5) · 40, y = (4,5 − zeile) · 40 (zeile 1 = oben = Schwarz).</li><li>Figur <b>Cursor</b> (Kostüm <code>Rahmen</code>) und Figur <b>Stein</b> mit 12 Kostümen, die <b>exakt</b> so heißen wie die Kürzel: <code>wK wD wT wL wS wB sK sD sT sL sS sB</code> (Kreis + Buchstabe genügt).</li><li>Erweiterung <b>Malstift</b> hinzufügen.</li></ul>',
      ctrl: [['pad', 'WÄHLEN', 'Controller: Steuerkreuz + WÄHLEN']], code: [] },
    { t: 'Aufstellung importieren', time: '≈ 5 Min.',
      goal: 'Die Startaufstellung liegt in einer Liste und wird bei jedem Spielstart ins Brett kopiert.',
      html: '<p>Lege zwei Listen an: <code>Aufstellung</code> und <code>Brett</code>. Lade die Datei herunter und importiere sie in <code>Aufstellung</code> (Rechtsklick auf die Liste auf der Bühne → <b>importieren</b>). Das Brett wird beim Start daraus kopiert — so ist jedes Spiel wieder frisch.</p><p style="margin-top:.7rem"><button class="btn" type="button" data-dl="aufstellung">⬇ aufstellung.txt herunterladen</button></p>',
      code: [['Cursor · Start', 'lst: lösche alles aus [Brett]\nvar: setze [i] auf (1)\nctl: wiederhole (64) mal\n  lst: füge {lst Element {var i} von [Aufstellung]} zu [Brett] hinzu\n  var: ändere [i] um (1)']] },
    { t: 'Brett zeichnen', time: '≈ 5 Min.',
      goal: 'Die Figur „Stein“ stempelt alle Figuren aus der Liste aufs Brett.',
      html: '<p>Der Stein-Figur schickst du die Nachricht <code>zeichnen</code>. Dann läuft sie alle 64 Felder ab, wechselt zum passenden Kostüm und hinterlässt einen Abdruck. Wichtig: Häkchen bei <b>„Ohne Bildschirmaktualisierung laufen lassen“</b>.</p>',
      tip: 'Der Cursor ruft <code>sende [zeichnen] an alle und warte</code> auf — so ist das Brett fertig, bevor es weitergeht.',
      code: [['Stein', 'ev: Wenn ich [zeichnen] empfange\nmy: zeichne Brett\n\ndef: Definiere zeichne Brett\npen: lösche alles\nlook: zeige dich\nvar: setze [k] auf (1)\nctl: wiederhole (64) mal\n  ctl: falls ⟨op nicht ⟨op {lst Element {var k} von [Brett]} = (--)⟩⟩, dann\n    look: wechsle zu Kostüm {lst Element {var k} von [Brett]}\n    mot: gehe zu x: {op {op {op {op {var k} - (1)} mod (8)} - (3.5)} * (40)} y: {op {op (3.5) - {op [abrunden] von {op {op {var k} - (1)} / (8)}}} * (40)}\n    pen: hinterlasse Abdruck\n  var: ändere [k] um (1)\nlook: verstecke dich']] },
    { t: 'Wählen & Ziehen', time: '≈ 7 Min.',
      goal: 'Eigene Figur wählen, Zielfeld wählen, Figur springt — noch ohne Regeln.',
      html: '<p>Variablen <code>farbe</code> (w/s), <code>phase</code>, <code>von</code>, <code>vonS</code>, <code>vonZ</code>, <code>Ziel</code>. Steht auf dem Feld eine eigene Figur, wird sie (neu) gewählt. Sonst — falls schon gewählt — wird gezogen. Vorerst ist jeder Zug erlaubt.</p>',
      code: [['Cursor', 'def: Definiere wähle oder ziehe\nvar: setze [Nr] auf {op {op {op {var zeile} - (1)} * (8)} + {var spalte}}\nvar: setze [Ziel] auf {lst Element {var Nr} von [Brett]}\nctl: falls ⟨op {op Zeichen (1) von {var Ziel}} = {var farbe}⟩, dann\n  var: setze [von] auf {var Nr}\n  var: setze [vonS] auf {var spalte}\n  var: setze [vonZ] auf {var zeile}\n  var: setze [phase] auf (ziehen)\n  look: sage {var Ziel} für (0.5) Sekunden\nctl: sonst\n  ctl: falls ⟨op {var phase} = (ziehen)⟩, dann\n    var: setze [erlaubt] auf (1)\n    note: ab Stufe 5: prüfe Zug\n    ctl: falls ⟨op {var erlaubt} = (1)⟩, dann\n      lst: ersetze Element {var Nr} von [Brett] durch {lst Element {var von} von [Brett]}\n      lst: ersetze Element {var von} von [Brett] durch (--)\n      ctl: falls ⟨op {var farbe} = (w)⟩, dann\n        var: setze [farbe] auf (s)\n      ctl: sonst\n        var: setze [farbe] auf (w)\n      ev: sende [zeichnen] an alle und warte\n    var: setze [phase] auf (wählen)']] },
    { t: 'Regeln I: Springer, König, Bauer', time: '≈ 8 Min.',
      goal: 'Der Block „prüfe Zug“ erlaubt nur regelgerechte Züge.',
      html: '<p>Aus Start (vonS | vonZ) und Ziel (spalte | zeile) werden <code>dx</code>, <code>dy</code> und ihre Beträge <code>adx</code>, <code>ady</code>. Für jeden Figurentyp eine Verzweigung. Weiß zieht nach oben (dy = −1), Schwarz nach unten (dy = +1).</p>',
      tip: 'Bauer: gerade nur auf leere Felder (1 Schritt, vom Start aus auch 2), schräg nur zum Schlagen.',
      code: [['Cursor', 'def: Definiere prüfe Zug\nvar: setze [dx] auf {op {var spalte} - {var vonS}}\nvar: setze [dy] auf {op {var zeile} - {var vonZ}}\nvar: setze [adx] auf {op [Betrag] von {var dx}}\nvar: setze [ady] auf {op [Betrag] von {var dy}}\nvar: setze [typ] auf {op Zeichen (2) von {lst Element {var von} von [Brett]}}\nvar: setze [erlaubt] auf (0)\nctl: falls ⟨op {var typ} = (S)⟩, dann\n  ctl: falls ⟨op ⟨op ⟨op {var adx} = (1)⟩ und ⟨op {var ady} = (2)⟩⟩ oder ⟨op ⟨op {var adx} = (2)⟩ und ⟨op {var ady} = (1)⟩⟩⟩, dann\n    var: setze [erlaubt] auf (1)\nctl: falls ⟨op {var typ} = (K)⟩, dann\n  ctl: falls ⟨op ⟨op {var adx} < (2)⟩ und ⟨op {var ady} < (2)⟩⟩, dann\n    var: setze [erlaubt] auf (1)\nctl: falls ⟨op {var typ} = (B)⟩, dann\n  my: prüfe Bauer\nnote: Stufe 6: T, L, D'], ['Cursor · Bauer', 'def: Definiere prüfe Bauer\nctl: falls ⟨op {var farbe} = (w)⟩, dann\n  var: setze [r] auf (-1)\n  var: setze [startZeile] auf (7)\nctl: sonst\n  var: setze [r] auf (1)\n  var: setze [startZeile] auf (2)\nctl: falls ⟨op ⟨op {var dx} = (0)⟩ und ⟨op {var Ziel} = (--)⟩⟩, dann\n  ctl: falls ⟨op {var dy} = {var r}⟩, dann\n    var: setze [erlaubt] auf (1)\n  ctl: falls ⟨op ⟨op {var dy} = {op (2) * {var r}}⟩ und ⟨op {var vonZ} = {var startZeile}⟩⟩, dann\n    ctl: falls ⟨op {lst Element {op {op {op {op {var vonZ} + {var r}} - (1)} * (8)} + {var vonS}} von [Brett]} = (--)⟩, dann\n      var: setze [erlaubt] auf (1)\nctl: falls ⟨op ⟨op {var adx} = (1)⟩ und ⟨op {var dy} = {var r}⟩⟩, dann\n  ctl: falls ⟨op nicht ⟨op {var Ziel} = (--)⟩⟩, dann\n    var: setze [erlaubt] auf (1)']] },
    { t: 'Regeln II: Turm, Läufer, Dame', time: '≈ 8 Min.',
      goal: 'Langschrittige Figuren ziehen nur, wenn der Weg frei ist.',
      html: '<p>Der Block <code>prüfe Weg</code> berechnet die Schrittzahl (größerer der beiden Beträge) und die Schrittrichtung <code>sx</code>, <code>sy</code> (−1, 0 oder 1). Dann prüft er jedes Feld <b>zwischen</b> Start und Ziel.</p>',
      code: [['Cursor · in „prüfe Zug“ ergänzen', 'ctl: falls ⟨op {var typ} = (T)⟩, dann\n  ctl: falls ⟨op ⟨op {var dx} = (0)⟩ oder ⟨op {var dy} = (0)⟩⟩, dann\n    my: prüfe Weg\nctl: falls ⟨op {var typ} = (L)⟩, dann\n  ctl: falls ⟨op {var adx} = {var ady}⟩, dann\n    my: prüfe Weg\nctl: falls ⟨op {var typ} = (D)⟩, dann\n  ctl: falls ⟨op ⟨op ⟨op {var dx} = (0)⟩ oder ⟨op {var dy} = (0)⟩⟩ oder ⟨op {var adx} = {var ady}⟩⟩, dann\n    my: prüfe Weg'], ['Cursor · prüfe Weg', 'def: Definiere prüfe Weg\nctl: falls ⟨op {var adx} > {var ady}⟩, dann\n  var: setze [schritte] auf {var adx}\nctl: sonst\n  var: setze [schritte] auf {var ady}\nvar: setze [sx] auf {op {var dx} / {var schritte}}\nvar: setze [sy] auf {op {var dy} / {var schritte}}\nvar: setze [s] auf {op {var vonS} + {var sx}}\nvar: setze [z] auf {op {var vonZ} + {var sy}}\nvar: setze [erlaubt] auf (1)\nctl: wiederhole {op {var schritte} - (1)} mal\n  ctl: falls ⟨op nicht ⟨op {lst Element {op {op {op {var z} - (1)} * (8)} + {var s}} von [Brett]} = (--)⟩⟩, dann\n    var: setze [erlaubt] auf (0)\n  var: ändere [s] um {var sx}\n  var: ändere [z] um {var sy}']] },
    { t: 'Spielende & Umwandlung', time: 'Bonus',
      goal: 'Königsfang beendet das Spiel, Bauern auf der letzten Reihe werden zur Dame.',
      html: '<p>Direkt <b>vor</b> dem Ziehen prüfen, ob auf dem Zielfeld ein König steht. <b>Nach</b> dem Ziehen: Ist ein Bauer auf Zeile 1 oder 8 angekommen, wird aus ihm eine Dame.</p>',
      code: [['Cursor · im erlaubten Zug ergänzen', 'ctl: falls ⟨op {op Zeichen (2) von {var Ziel}} = (K)⟩, dann\n  var: setze [Sieger] auf {var farbe}\nnote: … Figur ziehen (Stufe 4) …\nctl: falls ⟨op ⟨op {var typ} = (B)⟩ und ⟨op ⟨op {var zeile} = (1)⟩ oder ⟨op {var zeile} = (8)⟩⟩⟩, dann\n  lst: ersetze Element {var Nr} von [Brett] durch {op verbinde {var farbe} und (D)}']] }
  ],
  setup: [['Figuren', 'Cursor (Kostüm Rahmen) · Stein (12 Kostüme wK … sB)'], ['Variablen', 'farbe · phase · spalte · zeile · Nr · Ziel · von · vonS · vonZ · dx · dy · adx · ady · typ · erlaubt · r · startZeile · schritte · sx · sy · s · z · i · k · Sieger'], ['Listen', 'Aufstellung (importiert) · Brett (64)'], ['Bühne', '8 × 8-Brett, Feld = 40 px · Erweiterung Malstift']],
  plan: [
    ['Cursor · Hauptskript', 'ev: Wenn ⚑ angeklickt wird\nlst: lösche alles aus [Brett]\nvar: setze [i] auf (1)\nctl: wiederhole (64) mal\n  lst: füge {lst Element {var i} von [Aufstellung]} zu [Brett] hinzu\n  var: ändere [i] um (1)\nvar: setze [farbe] auf (w)\nvar: setze [phase] auf (wählen)\nvar: setze [Sieger] auf (-)\nvar: setze [spalte] auf (5)\nvar: setze [zeile] auf (7)\nlook: wechsle zu Kostüm [Rahmen]\nev: sende [zeichnen] an alle und warte\nctl: wiederhole bis ⟨op nicht ⟨op {var Sieger} = (-)⟩⟩\n  my: steuere Cursor\n  mot: gehe zu x: {op {op {var spalte} - (4.5)} * (40)} y: {op {op (4.5) - {var zeile}} * (40)}\n  ctl: falls ⟨sen Taste [Leertaste] gedrückt?⟩, dann\n    my: wähle oder ziehe\n    ctl: warte bis ⟨op nicht ⟨sen Taste [Leertaste] gedrückt?⟩⟩\nctl: falls ⟨op {var Sieger} = (w)⟩, dann\n  look: sage (Weiß gewinnt!)\nctl: sonst\n  look: sage (Schwarz gewinnt!)'],
    ['Cursor · steuere Cursor', 'def: Definiere steuere Cursor\nctl: falls ⟨op ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩ und ⟨op {var spalte} < (8)⟩⟩, dann\n  var: ändere [spalte] um (1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach rechts] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach links] gedrückt?⟩ und ⟨op {var spalte} > (1)⟩⟩, dann\n  var: ändere [spalte] um (-1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach links] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach unten] gedrückt?⟩ und ⟨op {var zeile} < (8)⟩⟩, dann\n  var: ändere [zeile] um (1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach unten] gedrückt?⟩⟩\nctl: falls ⟨op ⟨sen Taste [Pfeil nach oben] gedrückt?⟩ und ⟨op {var zeile} > (1)⟩⟩, dann\n  var: ändere [zeile] um (-1)\n  ctl: warte bis ⟨op nicht ⟨sen Taste [Pfeil nach oben] gedrückt?⟩⟩'],
    ['Cursor · wähle oder ziehe', 'def: Definiere wähle oder ziehe\nvar: setze [Nr] auf {op {op {op {var zeile} - (1)} * (8)} + {var spalte}}\nvar: setze [Ziel] auf {lst Element {var Nr} von [Brett]}\nctl: falls ⟨op {op Zeichen (1) von {var Ziel}} = {var farbe}⟩, dann\n  var: setze [von] auf {var Nr}\n  var: setze [vonS] auf {var spalte}\n  var: setze [vonZ] auf {var zeile}\n  var: setze [phase] auf (ziehen)\n  look: sage {var Ziel} für (0.5) Sekunden\nctl: sonst\n  ctl: falls ⟨op {var phase} = (ziehen)⟩, dann\n    my: prüfe Zug\n    ctl: falls ⟨op {var erlaubt} = (1)⟩, dann\n      ctl: falls ⟨op {op Zeichen (2) von {var Ziel}} = (K)⟩, dann\n        var: setze [Sieger] auf {var farbe}\n      lst: ersetze Element {var Nr} von [Brett] durch {lst Element {var von} von [Brett]}\n      lst: ersetze Element {var von} von [Brett] durch (--)\n      ctl: falls ⟨op ⟨op {var typ} = (B)⟩ und ⟨op ⟨op {var zeile} = (1)⟩ oder ⟨op {var zeile} = (8)⟩⟩⟩, dann\n        lst: ersetze Element {var Nr} von [Brett] durch {op verbinde {var farbe} und (D)}\n      ctl: falls ⟨op {var farbe} = (w)⟩, dann\n        var: setze [farbe] auf (s)\n      ctl: sonst\n        var: setze [farbe] auf (w)\n      ev: sende [zeichnen] an alle und warte\n    ctl: sonst\n      look: sage (Zug nicht erlaubt) für (1) Sekunden\n    var: setze [phase] auf (wählen)'],
    ['Cursor · prüfe Zug', 'def: Definiere prüfe Zug\nvar: setze [dx] auf {op {var spalte} - {var vonS}}\nvar: setze [dy] auf {op {var zeile} - {var vonZ}}\nvar: setze [adx] auf {op [Betrag] von {var dx}}\nvar: setze [ady] auf {op [Betrag] von {var dy}}\nvar: setze [typ] auf {op Zeichen (2) von {lst Element {var von} von [Brett]}}\nvar: setze [erlaubt] auf (0)\nctl: falls ⟨op {var typ} = (S)⟩, dann\n  ctl: falls ⟨op ⟨op ⟨op {var adx} = (1)⟩ und ⟨op {var ady} = (2)⟩⟩ oder ⟨op ⟨op {var adx} = (2)⟩ und ⟨op {var ady} = (1)⟩⟩⟩, dann\n    var: setze [erlaubt] auf (1)\nctl: falls ⟨op {var typ} = (K)⟩, dann\n  ctl: falls ⟨op ⟨op {var adx} < (2)⟩ und ⟨op {var ady} < (2)⟩⟩, dann\n    var: setze [erlaubt] auf (1)\nctl: falls ⟨op {var typ} = (T)⟩, dann\n  ctl: falls ⟨op ⟨op {var dx} = (0)⟩ oder ⟨op {var dy} = (0)⟩⟩, dann\n    my: prüfe Weg\nctl: falls ⟨op {var typ} = (L)⟩, dann\n  ctl: falls ⟨op {var adx} = {var ady}⟩, dann\n    my: prüfe Weg\nctl: falls ⟨op {var typ} = (D)⟩, dann\n  ctl: falls ⟨op ⟨op ⟨op {var dx} = (0)⟩ oder ⟨op {var dy} = (0)⟩⟩ oder ⟨op {var adx} = {var ady}⟩⟩, dann\n    my: prüfe Weg\nctl: falls ⟨op {var typ} = (B)⟩, dann\n  my: prüfe Bauer'],
    ['Cursor · prüfe Weg', 'def: Definiere prüfe Weg\nctl: falls ⟨op {var adx} > {var ady}⟩, dann\n  var: setze [schritte] auf {var adx}\nctl: sonst\n  var: setze [schritte] auf {var ady}\nvar: setze [sx] auf {op {var dx} / {var schritte}}\nvar: setze [sy] auf {op {var dy} / {var schritte}}\nvar: setze [s] auf {op {var vonS} + {var sx}}\nvar: setze [z] auf {op {var vonZ} + {var sy}}\nvar: setze [erlaubt] auf (1)\nctl: wiederhole {op {var schritte} - (1)} mal\n  ctl: falls ⟨op nicht ⟨op {lst Element {op {op {op {var z} - (1)} * (8)} + {var s}} von [Brett]} = (--)⟩⟩, dann\n    var: setze [erlaubt] auf (0)\n  var: ändere [s] um {var sx}\n  var: ändere [z] um {var sy}'],
    ['Cursor · prüfe Bauer', 'def: Definiere prüfe Bauer\nctl: falls ⟨op {var farbe} = (w)⟩, dann\n  var: setze [r] auf (-1)\n  var: setze [startZeile] auf (7)\nctl: sonst\n  var: setze [r] auf (1)\n  var: setze [startZeile] auf (2)\nctl: falls ⟨op ⟨op {var dx} = (0)⟩ und ⟨op {var Ziel} = (--)⟩⟩, dann\n  ctl: falls ⟨op {var dy} = {var r}⟩, dann\n    var: setze [erlaubt] auf (1)\n  ctl: falls ⟨op ⟨op {var dy} = {op (2) * {var r}}⟩ und ⟨op {var vonZ} = {var startZeile}⟩⟩, dann\n    ctl: falls ⟨op {lst Element {op {op {op {op {var vonZ} + {var r}} - (1)} * (8)} + {var vonS}} von [Brett]} = (--)⟩, dann\n      var: setze [erlaubt] auf (1)\nctl: falls ⟨op ⟨op {var adx} = (1)⟩ und ⟨op {var dy} = {var r}⟩⟩, dann\n  ctl: falls ⟨op nicht ⟨op {var Ziel} = (--)⟩⟩, dann\n    var: setze [erlaubt] auf (1)'],
    ['Stein · zeichne Brett (ohne Bildschirmaktualisierung)', 'ev: Wenn ich [zeichnen] empfange\nmy: zeichne Brett\n\ndef: Definiere zeichne Brett\npen: lösche alles\nlook: zeige dich\nvar: setze [k] auf (1)\nctl: wiederhole (64) mal\n  ctl: falls ⟨op nicht ⟨op {lst Element {var k} von [Brett]} = (--)⟩⟩, dann\n    look: wechsle zu Kostüm {lst Element {var k} von [Brett]}\n    mot: gehe zu x: {op {op {op {op {var k} - (1)} mod (8)} - (3.5)} * (40)} y: {op {op (3.5) - {op [abrunden] von {op {op {var k} - (1)} / (8)}}} * (40)}\n    pen: hinterlasse Abdruck\n  var: ändere [k] um (1)\nlook: verstecke dich']
  ],
  extra: '<b>Weiter geht’s:</b> Die gewählte Figur markieren (zweites Kostüm „Auswahl“ stempeln), mit <code>Maustaste gedrückt?</code> (CLICK) die Wahl abbrechen, oder Rochade einbauen.'
}
];
